// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB88dz1DJZfvkqPd9mayE5k7unIfe396tY',
    appId: '1:306446799427:web:ba0ec16fcf59455cbffaf6',
    messagingSenderId: '306446799427',
    projectId: 'flutter-janganan',
    authDomain: 'flutter-janganan.firebaseapp.com',
    storageBucket: 'flutter-janganan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTviC_OuHPRCi6u4fKAnSjwWRs3vaVZZw',
    appId: '1:306446799427:android:3b53512b0f87b45ebffaf6',
    messagingSenderId: '306446799427',
    projectId: 'flutter-janganan',
    storageBucket: 'flutter-janganan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__k6gGaSCBbP0wRXfpJQeyiXnJHtmoN4',
    appId: '1:306446799427:ios:7c2638bdbe41fcd7bffaf6',
    messagingSenderId: '306446799427',
    projectId: 'flutter-janganan',
    storageBucket: 'flutter-janganan.appspot.com',
    iosClientId: '306446799427-8jlt183egls6qnsinhjvilqtvs1e6l42.apps.googleusercontent.com',
    iosBundleId: 'com.example.janganan',
  );
}
